apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cake-app
  name: cake-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cake-app
    spec:
      containers:
      - image: kadasz/cake-app:v1
        name: cake-app
        resources: {}
status: {}
