apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cake-app
  name: cake-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cake-app
    spec:
      containers:
      - image: kadasz/cake-app:1.0.5
        name: cake-app
        env:
        - name: APP_BG
          value: "gray"
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 2500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cake-app-svc
spec:
  type: NodePort
  selector:
    app: cake-app
  ports:
    - nodePort: 32080
      protocol: TCP
      port: 8080
