apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cake-app
  name: cake-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cake-app
    spec:
      securityContext:
        runAsUser: 9999
        runAsGroup: 9999
        #fsGroup: 2000
      containers:
      - image: kadasz/cake-app:1.0.5
        name: cake-app
        env:
        - name: APP_BG
          value: "gray"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: "/health/check"
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: "/health/check"
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            cpu: 150m
            memory: 250Mi
          limits:
            cpu: 200m
            memory: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cake-app-svc
spec:
  type: NodePort
  selector:
    app: cake-app
  ports:
    - nodePort: 32080
      protocol: TCP
      port: 8080
